/* Borrar tabla */
DROP TABLE ALUMNADO;

/* Crear tabla */
CREATE TABLE ALUMNADO(
	DNI 	VARCHAR2(10),	
	NOMBRE 	VARCHAR2(30)  NOT NULL, 
	SEXO 	CHAR NOT NULL CONSTRAINT ALU_SEXO_CK CHECK (SEXO IN ('M','F')),
	CURSO 	NUMBER(1),
	FECHA_ALTA DATE,
	CONSTRAINT 	ALU_DNI_PK 	PRIMARY KEY(DNI),
	CONSTRAINT	ALU_EDA_CK 	CHECK (EDAD BETWEEN 5 AND 20), 
	CONSTRAINT 	ALU_NOM_CK  CHECK (NOMBRE=UPPER(NOMBRE)), 
	CONSTRAINT 	ALU_CUR_CK  CHECK (CURSO IN(1,2,3)) );